/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ConversationId = bigint;
export interface ConversationPublic {
  'id' : ConversationId,
  'lastMessageAt' : Timestamp,
  'unreadCountSeller' : bigint,
  'listingId' : ListingId,
  'buyerId' : UserId,
  'sellerId' : UserId,
  'unreadCountBuyer' : bigint,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type ExternalBlob = Uint8Array;
export type ListingCategory = { 'sarees' : null } |
  { 'accessories' : null } |
  { 'other' : null } |
  { 'footwear' : null } |
  { 'jewelry' : null } |
  { 'kurtis' : null } |
  { 'lehengas' : null } |
  { 'salwarSuits' : null };
export type ListingCondition = { 'fair' : null } |
  { 'good' : null } |
  { 'poor' : null } |
  { 'likeNew' : null } |
  { 'brandNew' : null };
export interface ListingFilter {
  'maxPrice' : [] | [bigint],
  'category' : [] | [ListingCategory],
  'keyword' : [] | [string],
  'minPrice' : [] | [bigint],
  'location' : [] | [string],
  'condition' : [] | [ListingCondition],
}
export type ListingId = bigint;
export interface ListingInput {
  'title' : string,
  'description' : string,
  'category' : ListingCategory,
  'price' : bigint,
  'location' : string,
  'condition' : ListingCondition,
  'images' : Array<ExternalBlob>,
}
export interface ListingPublic {
  'id' : ListingId,
  'status' : ListingStatus,
  'title' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'updatedAt' : Timestamp,
  'viewCount' : bigint,
  'category' : ListingCategory,
  'sellerId' : UserId,
  'price' : bigint,
  'location' : string,
  'condition' : ListingCondition,
  'images' : Array<ExternalBlob>,
}
export type ListingStatus = { 'active' : null } |
  { 'expired' : null } |
  { 'sold' : null };
export type MessageId = bigint;
export interface MessagePublic {
  'id' : MessageId,
  'content' : string,
  'isRead' : boolean,
  'sentAt' : Timestamp,
  'conversationId' : ConversationId,
  'senderId' : UserId,
}
export interface PageResult {
  'total' : bigint,
  'offset' : bigint,
  'limit' : bigint,
  'items' : Array<ListingPublic>,
}
export interface PageResult_1 {
  'total' : bigint,
  'offset' : bigint,
  'limit' : bigint,
  'items' : Array<MessagePublic>,
}
export interface PageResult_2 {
  'total' : bigint,
  'offset' : bigint,
  'limit' : bigint,
  'items' : Array<ConversationPublic>,
}
export type Result = { 'ok' : null } |
  { 'err' : Error };
export interface SendMessageInput {
  'content' : string,
  'listingId' : ListingId,
  'conversationId' : [] | [ConversationId],
  'recipientId' : UserId,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfileInput {
  'bio' : [] | [string],
  'name' : string,
  'avatarUrl' : [] | [string],
  'phone' : [] | [string],
  'location' : [] | [string],
}
export interface UserProfilePublic {
  'id' : UserId,
  'bio' : [] | [string],
  'name' : string,
  'memberSince' : Timestamp,
  'avatarUrl' : [] | [string],
  'phone' : [] | [string],
  'location' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createListing' : ActorMethod<[ListingInput], ListingPublic>,
  'createUserProfile' : ActorMethod<[UserProfileInput], UserProfilePublic>,
  'deleteListing' : ActorMethod<[ListingId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversations' : ActorMethod<[bigint, bigint], PageResult_2>,
  'getFeaturedListings' : ActorMethod<[bigint, bigint], PageResult>,
  'getListing' : ActorMethod<[ListingId], [] | [ListingPublic]>,
  'getListingsBySeller' : ActorMethod<[UserId, bigint, bigint], PageResult>,
  'getMessages' : ActorMethod<[ConversationId, bigint, bigint], PageResult_1>,
  'getSimilarListings' : ActorMethod<
    [ListingCategory, string, ListingId, bigint, bigint],
    PageResult
  >,
  'getUnreadCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfilePublic]>,
  'incrementListingViewCount' : ActorMethod<[ListingId], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markMessagesRead' : ActorMethod<[ConversationId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfileInput], undefined>,
  'searchListings' : ActorMethod<[ListingFilter, bigint, bigint], PageResult>,
  'sendMessage' : ActorMethod<[SendMessageInput], MessagePublic>,
  'updateListing' : ActorMethod<[ListingId, ListingInput], ListingPublic>,
  'updateUserProfile' : ActorMethod<[UserProfileInput], UserProfilePublic>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];