/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ListingCategory = IDL.Variant({
  'sarees' : IDL.Null,
  'accessories' : IDL.Null,
  'other' : IDL.Null,
  'footwear' : IDL.Null,
  'jewelry' : IDL.Null,
  'kurtis' : IDL.Null,
  'lehengas' : IDL.Null,
  'salwarSuits' : IDL.Null,
});
export const ListingCondition = IDL.Variant({
  'fair' : IDL.Null,
  'good' : IDL.Null,
  'poor' : IDL.Null,
  'likeNew' : IDL.Null,
  'brandNew' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ListingInput = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'category' : ListingCategory,
  'price' : IDL.Nat,
  'location' : IDL.Text,
  'condition' : ListingCondition,
  'images' : IDL.Vec(ExternalBlob),
});
export const ListingId = IDL.Nat;
export const ListingStatus = IDL.Variant({
  'active' : IDL.Null,
  'expired' : IDL.Null,
  'sold' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const UserId = IDL.Principal;
export const ListingPublic = IDL.Record({
  'id' : ListingId,
  'status' : ListingStatus,
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'updatedAt' : Timestamp,
  'viewCount' : IDL.Nat,
  'category' : ListingCategory,
  'sellerId' : UserId,
  'price' : IDL.Nat,
  'location' : IDL.Text,
  'condition' : ListingCondition,
  'images' : IDL.Vec(ExternalBlob),
});
export const UserProfileInput = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'avatarUrl' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
  'location' : IDL.Opt(IDL.Text),
});
export const UserProfilePublic = IDL.Record({
  'id' : UserId,
  'bio' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'memberSince' : Timestamp,
  'avatarUrl' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
  'location' : IDL.Opt(IDL.Text),
});
export const ConversationId = IDL.Nat;
export const ConversationPublic = IDL.Record({
  'id' : ConversationId,
  'lastMessageAt' : Timestamp,
  'unreadCountSeller' : IDL.Nat,
  'listingId' : ListingId,
  'buyerId' : UserId,
  'sellerId' : UserId,
  'unreadCountBuyer' : IDL.Nat,
});
export const PageResult_2 = IDL.Record({
  'total' : IDL.Nat,
  'offset' : IDL.Nat,
  'limit' : IDL.Nat,
  'items' : IDL.Vec(ConversationPublic),
});
export const PageResult = IDL.Record({
  'total' : IDL.Nat,
  'offset' : IDL.Nat,
  'limit' : IDL.Nat,
  'items' : IDL.Vec(ListingPublic),
});
export const MessageId = IDL.Nat;
export const MessagePublic = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'isRead' : IDL.Bool,
  'sentAt' : Timestamp,
  'conversationId' : ConversationId,
  'senderId' : UserId,
});
export const PageResult_1 = IDL.Record({
  'total' : IDL.Nat,
  'offset' : IDL.Nat,
  'limit' : IDL.Nat,
  'items' : IDL.Vec(MessagePublic),
});
export const ListingFilter = IDL.Record({
  'maxPrice' : IDL.Opt(IDL.Nat),
  'category' : IDL.Opt(ListingCategory),
  'keyword' : IDL.Opt(IDL.Text),
  'minPrice' : IDL.Opt(IDL.Nat),
  'location' : IDL.Opt(IDL.Text),
  'condition' : IDL.Opt(ListingCondition),
});
export const SendMessageInput = IDL.Record({
  'content' : IDL.Text,
  'listingId' : ListingId,
  'conversationId' : IDL.Opt(ConversationId),
  'recipientId' : UserId,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createListing' : IDL.Func([ListingInput], [ListingPublic], []),
  'createUserProfile' : IDL.Func([UserProfileInput], [UserProfilePublic], []),
  'deleteListing' : IDL.Func([ListingId], [], []),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(UserProfilePublic)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversations' : IDL.Func([IDL.Nat, IDL.Nat], [PageResult_2], ['query']),
  'getFeaturedListings' : IDL.Func([IDL.Nat, IDL.Nat], [PageResult], ['query']),
  'getListing' : IDL.Func([ListingId], [IDL.Opt(ListingPublic)], ['query']),
  'getListingsBySeller' : IDL.Func(
      [UserId, IDL.Nat, IDL.Nat],
      [PageResult],
      ['query'],
    ),
  'getMessages' : IDL.Func(
      [ConversationId, IDL.Nat, IDL.Nat],
      [PageResult_1],
      ['query'],
    ),
  'getSimilarListings' : IDL.Func(
      [ListingCategory, IDL.Text, ListingId, IDL.Nat, IDL.Nat],
      [PageResult],
      ['query'],
    ),
  'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [UserId],
      [IDL.Opt(UserProfilePublic)],
      ['query'],
    ),
  'incrementListingViewCount' : IDL.Func([ListingId], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markMessagesRead' : IDL.Func([ConversationId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfileInput], [], []),
  'searchListings' : IDL.Func(
      [ListingFilter, IDL.Nat, IDL.Nat],
      [PageResult],
      ['query'],
    ),
  'sendMessage' : IDL.Func([SendMessageInput], [MessagePublic], []),
  'updateListing' : IDL.Func([ListingId, ListingInput], [ListingPublic], []),
  'updateUserProfile' : IDL.Func([UserProfileInput], [UserProfilePublic], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ListingCategory = IDL.Variant({
    'sarees' : IDL.Null,
    'accessories' : IDL.Null,
    'other' : IDL.Null,
    'footwear' : IDL.Null,
    'jewelry' : IDL.Null,
    'kurtis' : IDL.Null,
    'lehengas' : IDL.Null,
    'salwarSuits' : IDL.Null,
  });
  const ListingCondition = IDL.Variant({
    'fair' : IDL.Null,
    'good' : IDL.Null,
    'poor' : IDL.Null,
    'likeNew' : IDL.Null,
    'brandNew' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ListingInput = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'category' : ListingCategory,
    'price' : IDL.Nat,
    'location' : IDL.Text,
    'condition' : ListingCondition,
    'images' : IDL.Vec(ExternalBlob),
  });
  const ListingId = IDL.Nat;
  const ListingStatus = IDL.Variant({
    'active' : IDL.Null,
    'expired' : IDL.Null,
    'sold' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const UserId = IDL.Principal;
  const ListingPublic = IDL.Record({
    'id' : ListingId,
    'status' : ListingStatus,
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'updatedAt' : Timestamp,
    'viewCount' : IDL.Nat,
    'category' : ListingCategory,
    'sellerId' : UserId,
    'price' : IDL.Nat,
    'location' : IDL.Text,
    'condition' : ListingCondition,
    'images' : IDL.Vec(ExternalBlob),
  });
  const UserProfileInput = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'avatarUrl' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
    'location' : IDL.Opt(IDL.Text),
  });
  const UserProfilePublic = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'memberSince' : Timestamp,
    'avatarUrl' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
    'location' : IDL.Opt(IDL.Text),
  });
  const ConversationId = IDL.Nat;
  const ConversationPublic = IDL.Record({
    'id' : ConversationId,
    'lastMessageAt' : Timestamp,
    'unreadCountSeller' : IDL.Nat,
    'listingId' : ListingId,
    'buyerId' : UserId,
    'sellerId' : UserId,
    'unreadCountBuyer' : IDL.Nat,
  });
  const PageResult_2 = IDL.Record({
    'total' : IDL.Nat,
    'offset' : IDL.Nat,
    'limit' : IDL.Nat,
    'items' : IDL.Vec(ConversationPublic),
  });
  const PageResult = IDL.Record({
    'total' : IDL.Nat,
    'offset' : IDL.Nat,
    'limit' : IDL.Nat,
    'items' : IDL.Vec(ListingPublic),
  });
  const MessageId = IDL.Nat;
  const MessagePublic = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'isRead' : IDL.Bool,
    'sentAt' : Timestamp,
    'conversationId' : ConversationId,
    'senderId' : UserId,
  });
  const PageResult_1 = IDL.Record({
    'total' : IDL.Nat,
    'offset' : IDL.Nat,
    'limit' : IDL.Nat,
    'items' : IDL.Vec(MessagePublic),
  });
  const ListingFilter = IDL.Record({
    'maxPrice' : IDL.Opt(IDL.Nat),
    'category' : IDL.Opt(ListingCategory),
    'keyword' : IDL.Opt(IDL.Text),
    'minPrice' : IDL.Opt(IDL.Nat),
    'location' : IDL.Opt(IDL.Text),
    'condition' : IDL.Opt(ListingCondition),
  });
  const SendMessageInput = IDL.Record({
    'content' : IDL.Text,
    'listingId' : ListingId,
    'conversationId' : IDL.Opt(ConversationId),
    'recipientId' : UserId,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createListing' : IDL.Func([ListingInput], [ListingPublic], []),
    'createUserProfile' : IDL.Func([UserProfileInput], [UserProfilePublic], []),
    'deleteListing' : IDL.Func([ListingId], [], []),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(UserProfilePublic)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversations' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [PageResult_2],
        ['query'],
      ),
    'getFeaturedListings' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [PageResult],
        ['query'],
      ),
    'getListing' : IDL.Func([ListingId], [IDL.Opt(ListingPublic)], ['query']),
    'getListingsBySeller' : IDL.Func(
        [UserId, IDL.Nat, IDL.Nat],
        [PageResult],
        ['query'],
      ),
    'getMessages' : IDL.Func(
        [ConversationId, IDL.Nat, IDL.Nat],
        [PageResult_1],
        ['query'],
      ),
    'getSimilarListings' : IDL.Func(
        [ListingCategory, IDL.Text, ListingId, IDL.Nat, IDL.Nat],
        [PageResult],
        ['query'],
      ),
    'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [UserId],
        [IDL.Opt(UserProfilePublic)],
        ['query'],
      ),
    'incrementListingViewCount' : IDL.Func([ListingId], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markMessagesRead' : IDL.Func([ConversationId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfileInput], [], []),
    'searchListings' : IDL.Func(
        [ListingFilter, IDL.Nat, IDL.Nat],
        [PageResult],
        ['query'],
      ),
    'sendMessage' : IDL.Func([SendMessageInput], [MessagePublic], []),
    'updateListing' : IDL.Func([ListingId, ListingInput], [ListingPublic], []),
    'updateUserProfile' : IDL.Func([UserProfileInput], [UserProfilePublic], []),
  });
};

export const init = ({ IDL }) => { return []; };