/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PageResult_2 {
    total: bigint;
    offset: bigint;
    limit: bigint;
    items: Array<ConversationPublic>;
}
export interface MessagePublic {
    id: MessageId;
    content: string;
    isRead: boolean;
    sentAt: Timestamp;
    conversationId: ConversationId;
    senderId: UserId;
}
export type Timestamp = bigint;
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface PageResult_1 {
    total: bigint;
    offset: bigint;
    limit: bigint;
    items: Array<MessagePublic>;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface ConversationPublic {
    id: ConversationId;
    lastMessageAt: Timestamp;
    unreadCountSeller: bigint;
    listingId: ListingId;
    buyerId: UserId;
    sellerId: UserId;
    unreadCountBuyer: bigint;
}
export interface UserProfilePublic {
    id: UserId;
    bio?: string;
    name: string;
    memberSince: Timestamp;
    avatarUrl?: string;
    phone?: string;
    location?: string;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type UserId = Principal;
export interface ListingInput {
    title: string;
    description: string;
    category: ListingCategory;
    price: bigint;
    location: string;
    condition: ListingCondition;
    images: Array<ExternalBlob>;
}
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface ListingPublic {
    id: ListingId;
    status: ListingStatus;
    title: string;
    createdAt: Timestamp;
    description: string;
    updatedAt: Timestamp;
    viewCount: bigint;
    category: ListingCategory;
    sellerId: UserId;
    price: bigint;
    location: string;
    condition: ListingCondition;
    images: Array<ExternalBlob>;
}
export type MessageId = bigint;
export type ListingId = bigint;
export interface ListingFilter {
    maxPrice?: bigint;
    category?: ListingCategory;
    keyword?: string;
    minPrice?: bigint;
    location?: string;
    condition?: ListingCondition;
}
export type ConversationId = bigint;
export interface SendMessageInput {
    content: string;
    listingId: ListingId;
    conversationId?: ConversationId;
    recipientId: UserId;
}
export interface PageResult {
    total: bigint;
    offset: bigint;
    limit: bigint;
    items: Array<ListingPublic>;
}
export interface UserProfileInput {
    bio?: string;
    name: string;
    avatarUrl?: string;
    phone?: string;
    location?: string;
}
export enum ListingCategory {
    sarees = "sarees",
    accessories = "accessories",
    other = "other",
    footwear = "footwear",
    jewelry = "jewelry",
    kurtis = "kurtis",
    lehengas = "lehengas",
    salwarSuits = "salwarSuits"
}
export enum ListingCondition {
    fair = "fair",
    good = "good",
    poor = "poor",
    likeNew = "likeNew",
    brandNew = "brandNew"
}
export enum ListingStatus {
    active = "active",
    expired = "expired",
    sold = "sold"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createListing(input: ListingInput): Promise<ListingPublic>;
    createUserProfile(input: UserProfileInput): Promise<UserProfilePublic>;
    deleteListing(id: ListingId): Promise<void>;
    getCallerUserProfile(): Promise<UserProfilePublic | null>;
    getCallerUserRole(): Promise<UserRole>;
    getConversations(offset: bigint, limit: bigint): Promise<PageResult_2>;
    getFeaturedListings(offset: bigint, limit: bigint): Promise<PageResult>;
    getListing(id: ListingId): Promise<ListingPublic | null>;
    getListingsBySeller(sellerId: UserId, offset: bigint, limit: bigint): Promise<PageResult>;
    getMessages(conversationId: ConversationId, offset: bigint, limit: bigint): Promise<PageResult_1>;
    getSimilarListings(category: ListingCategory, location: string, excludeId: ListingId, offset: bigint, limit: bigint): Promise<PageResult>;
    getUnreadCount(): Promise<bigint>;
    getUserProfile(userId: UserId): Promise<UserProfilePublic | null>;
    incrementListingViewCount(id: ListingId): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    markMessagesRead(conversationId: ConversationId): Promise<void>;
    saveCallerUserProfile(profile: UserProfileInput): Promise<void>;
    searchListings(filter: ListingFilter, offset: bigint, limit: bigint): Promise<PageResult>;
    sendMessage(input: SendMessageInput): Promise<MessagePublic>;
    updateListing(id: ListingId, input: ListingInput): Promise<ListingPublic>;
    updateUserProfile(input: UserProfileInput): Promise<UserProfilePublic>;
}
import type { ConversationId as _ConversationId, Error as _Error, ExternalBlob as _ExternalBlob, ListingCategory as _ListingCategory, ListingCondition as _ListingCondition, ListingFilter as _ListingFilter, ListingId as _ListingId, ListingInput as _ListingInput, ListingPublic as _ListingPublic, ListingStatus as _ListingStatus, PageResult as _PageResult, Result as _Result, SendMessageInput as _SendMessageInput, Timestamp as _Timestamp, UserId as _UserId, UserProfileInput as _UserProfileInput, UserProfilePublic as _UserProfilePublic, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createListing(arg0: ListingInput): Promise<ListingPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createListing(await to_candid_ListingInput_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ListingPublic_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createListing(await to_candid_ListingInput_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ListingPublic_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async createUserProfile(arg0: UserProfileInput): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createUserProfile(to_candid_UserProfileInput_n32(this._uploadFile, this._downloadFile, arg0));
                return from_candid_UserProfilePublic_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUserProfile(to_candid_UserProfileInput_n32(this._uploadFile, this._downloadFile, arg0));
            return from_candid_UserProfilePublic_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteListing(arg0: ListingId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteListing(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConversations(arg0: bigint, arg1: bigint): Promise<PageResult_2> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversations(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversations(arg0, arg1);
            return result;
        }
    }
    async getFeaturedListings(arg0: bigint, arg1: bigint): Promise<PageResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedListings(arg0, arg1);
                return from_candid_PageResult_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedListings(arg0, arg1);
            return from_candid_PageResult_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListing(arg0: ListingId): Promise<ListingPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getListing(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListing(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListingsBySeller(arg0: UserId, arg1: bigint, arg2: bigint): Promise<PageResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getListingsBySeller(arg0, arg1, arg2);
                return from_candid_PageResult_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListingsBySeller(arg0, arg1, arg2);
            return from_candid_PageResult_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(arg0: ConversationId, arg1: bigint, arg2: bigint): Promise<PageResult_1> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0, arg1, arg2);
            return result;
        }
    }
    async getSimilarListings(arg0: ListingCategory, arg1: string, arg2: ListingId, arg3: bigint, arg4: bigint): Promise<PageResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getSimilarListings(to_candid_ListingCategory_n16(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4);
                return from_candid_PageResult_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSimilarListings(to_candid_ListingCategory_n16(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4);
            return from_candid_PageResult_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnreadCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadCount();
            return result;
        }
    }
    async getUserProfile(arg0: UserId): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async incrementListingViewCount(arg0: ListingId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementListingViewCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementListingViewCount(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markMessagesRead(arg0: ConversationId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markMessagesRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markMessagesRead(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfileInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfileInput_n32(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfileInput_n32(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchListings(arg0: ListingFilter, arg1: bigint, arg2: bigint): Promise<PageResult> {
        if (this.processError) {
            try {
                const result = await this.actor.searchListings(to_candid_ListingFilter_n44(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_PageResult_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchListings(to_candid_ListingFilter_n44(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_PageResult_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendMessage(arg0: SendMessageInput): Promise<MessagePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(to_candid_SendMessageInput_n46(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(to_candid_SendMessageInput_n46(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateListing(arg0: ListingId, arg1: ListingInput): Promise<ListingPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.updateListing(arg0, await to_candid_ListingInput_n14(this._uploadFile, this._downloadFile, arg1));
                return from_candid_ListingPublic_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateListing(arg0, await to_candid_ListingInput_n14(this._uploadFile, this._downloadFile, arg1));
            return from_candid_ListingPublic_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUserProfile(arg0: UserProfileInput): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(to_candid_UserProfileInput_n32(this._uploadFile, this._downloadFile, arg0));
                return from_candid_UserProfilePublic_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(to_candid_UserProfileInput_n32(this._uploadFile, this._downloadFile, arg0));
            return from_candid_UserProfilePublic_n34(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Error_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_ListingCategory_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ListingCategory): ListingCategory {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_ListingCondition_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ListingCondition): ListingCondition {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
async function from_candid_ListingPublic_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ListingPublic): Promise<ListingPublic> {
    return await from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_ListingStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ListingStatus): ListingStatus {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
async function from_candid_PageResult_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PageResult): Promise<PageResult> {
    return await from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfilePublic_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfilePublic): UserProfilePublic {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfilePublic]): UserProfilePublic | null {
    return value.length === 0 ? null : from_candid_UserProfilePublic_n34(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ListingPublic]): Promise<ListingPublic | null> {
    return value.length === 0 ? null : await from_candid_ListingPublic_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ListingId;
    status: _ListingStatus;
    title: string;
    createdAt: _Timestamp;
    description: string;
    updatedAt: _Timestamp;
    viewCount: bigint;
    category: _ListingCategory;
    sellerId: _UserId;
    price: bigint;
    location: string;
    condition: _ListingCondition;
    images: Array<_ExternalBlob>;
}): Promise<{
    id: ListingId;
    status: ListingStatus;
    title: string;
    createdAt: Timestamp;
    description: string;
    updatedAt: Timestamp;
    viewCount: bigint;
    category: ListingCategory;
    sellerId: UserId;
    price: bigint;
    location: string;
    condition: ListingCondition;
    images: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        status: from_candid_ListingStatus_n24(_uploadFile, _downloadFile, value.status),
        title: value.title,
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: value.updatedAt,
        viewCount: value.viewCount,
        category: from_candid_ListingCategory_n26(_uploadFile, _downloadFile, value.category),
        sellerId: value.sellerId,
        price: value.price,
        location: value.location,
        condition: from_candid_ListingCondition_n28(_uploadFile, _downloadFile, value.condition),
        images: await from_candid_vec_n30(_uploadFile, _downloadFile, value.images)
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    bio: [] | [string];
    name: string;
    memberSince: _Timestamp;
    avatarUrl: [] | [string];
    phone: [] | [string];
    location: [] | [string];
}): {
    id: UserId;
    bio?: string;
    name: string;
    memberSince: Timestamp;
    avatarUrl?: string;
    phone?: string;
    location?: string;
} {
    return {
        id: value.id,
        bio: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.bio)),
        name: value.name,
        memberSince: value.memberSince,
        avatarUrl: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.avatarUrl)),
        phone: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.phone)),
        location: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.location))
    };
}
async function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    offset: bigint;
    limit: bigint;
    items: Array<_ListingPublic>;
}): Promise<{
    total: bigint;
    offset: bigint;
    limit: bigint;
    items: Array<ListingPublic>;
}> {
    return {
        total: value.total,
        offset: value.offset,
        limit: value.limit,
        items: await from_candid_vec_n42(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    expired: null;
} | {
    sold: null;
}): ListingStatus {
    return "active" in value ? ListingStatus.active : "expired" in value ? ListingStatus.expired : "sold" in value ? ListingStatus.sold : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sarees: null;
} | {
    accessories: null;
} | {
    other: null;
} | {
    footwear: null;
} | {
    jewelry: null;
} | {
    kurtis: null;
} | {
    lehengas: null;
} | {
    salwarSuits: null;
}): ListingCategory {
    return "sarees" in value ? ListingCategory.sarees : "accessories" in value ? ListingCategory.accessories : "other" in value ? ListingCategory.other : "footwear" in value ? ListingCategory.footwear : "jewelry" in value ? ListingCategory.jewelry : "kurtis" in value ? ListingCategory.kurtis : "lehengas" in value ? ListingCategory.lehengas : "salwarSuits" in value ? ListingCategory.salwarSuits : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fair: null;
} | {
    good: null;
} | {
    poor: null;
} | {
    likeNew: null;
} | {
    brandNew: null;
}): ListingCondition {
    return "fair" in value ? ListingCondition.fair : "good" in value ? ListingCondition.good : "poor" in value ? ListingCondition.poor : "likeNew" in value ? ListingCondition.likeNew : "brandNew" in value ? ListingCondition.brandNew : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n10(_uploadFile, _downloadFile, value.err)
    } : value;
}
async function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n31(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ListingPublic>): Promise<Array<ListingPublic>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ListingPublic_n22(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_ListingCategory_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingCategory): _ListingCategory {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_ListingCondition_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingCondition): _ListingCondition {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_ListingFilter_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingFilter): _ListingFilter {
    return to_candid_record_n45(_uploadFile, _downloadFile, value);
}
async function to_candid_ListingInput_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingInput): Promise<_ListingInput> {
    return await to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_SendMessageInput_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SendMessageInput): _SendMessageInput {
    return to_candid_record_n47(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfileInput_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfileInput): _UserProfileInput {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    description: string;
    category: ListingCategory;
    price: bigint;
    location: string;
    condition: ListingCondition;
    images: Array<ExternalBlob>;
}): Promise<{
    title: string;
    description: string;
    category: _ListingCategory;
    price: bigint;
    location: string;
    condition: _ListingCondition;
    images: Array<_ExternalBlob>;
}> {
    return {
        title: value.title,
        description: value.description,
        category: to_candid_ListingCategory_n16(_uploadFile, _downloadFile, value.category),
        price: value.price,
        location: value.location,
        condition: to_candid_ListingCondition_n18(_uploadFile, _downloadFile, value.condition),
        images: await to_candid_vec_n20(_uploadFile, _downloadFile, value.images)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio?: string;
    name: string;
    avatarUrl?: string;
    phone?: string;
    location?: string;
}): {
    bio: [] | [string];
    name: string;
    avatarUrl: [] | [string];
    phone: [] | [string];
    location: [] | [string];
} {
    return {
        bio: value.bio ? candid_some(value.bio) : candid_none(),
        name: value.name,
        avatarUrl: value.avatarUrl ? candid_some(value.avatarUrl) : candid_none(),
        phone: value.phone ? candid_some(value.phone) : candid_none(),
        location: value.location ? candid_some(value.location) : candid_none()
    };
}
function to_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    maxPrice?: bigint;
    category?: ListingCategory;
    keyword?: string;
    minPrice?: bigint;
    location?: string;
    condition?: ListingCondition;
}): {
    maxPrice: [] | [bigint];
    category: [] | [_ListingCategory];
    keyword: [] | [string];
    minPrice: [] | [bigint];
    location: [] | [string];
    condition: [] | [_ListingCondition];
} {
    return {
        maxPrice: value.maxPrice ? candid_some(value.maxPrice) : candid_none(),
        category: value.category ? candid_some(to_candid_ListingCategory_n16(_uploadFile, _downloadFile, value.category)) : candid_none(),
        keyword: value.keyword ? candid_some(value.keyword) : candid_none(),
        minPrice: value.minPrice ? candid_some(value.minPrice) : candid_none(),
        location: value.location ? candid_some(value.location) : candid_none(),
        condition: value.condition ? candid_some(to_candid_ListingCondition_n18(_uploadFile, _downloadFile, value.condition)) : candid_none()
    };
}
function to_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: string;
    listingId: ListingId;
    conversationId?: ConversationId;
    recipientId: UserId;
}): {
    content: string;
    listingId: _ListingId;
    conversationId: [] | [_ConversationId];
    recipientId: _UserId;
} {
    return {
        content: value.content,
        listingId: value.listingId,
        conversationId: value.conversationId ? candid_some(value.conversationId) : candid_none(),
        recipientId: value.recipientId
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingCategory): {
    sarees: null;
} | {
    accessories: null;
} | {
    other: null;
} | {
    footwear: null;
} | {
    jewelry: null;
} | {
    kurtis: null;
} | {
    lehengas: null;
} | {
    salwarSuits: null;
} {
    return value == ListingCategory.sarees ? {
        sarees: null
    } : value == ListingCategory.accessories ? {
        accessories: null
    } : value == ListingCategory.other ? {
        other: null
    } : value == ListingCategory.footwear ? {
        footwear: null
    } : value == ListingCategory.jewelry ? {
        jewelry: null
    } : value == ListingCategory.kurtis ? {
        kurtis: null
    } : value == ListingCategory.lehengas ? {
        lehengas: null
    } : value == ListingCategory.salwarSuits ? {
        salwarSuits: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingCondition): {
    fair: null;
} | {
    good: null;
} | {
    poor: null;
} | {
    likeNew: null;
} | {
    brandNew: null;
} {
    return value == ListingCondition.fair ? {
        fair: null
    } : value == ListingCondition.good ? {
        good: null
    } : value == ListingCondition.poor ? {
        poor: null
    } : value == ListingCondition.likeNew ? {
        likeNew: null
    } : value == ListingCondition.brandNew ? {
        brandNew: null
    } : value;
}
async function to_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n21(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
